// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProject1
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSIXProject1.9be5cbc9-f877-4879-b814-7004dace6eb3";
        public const string Name = "AI_TESTING_ENVIRONMENT";
        public const string Description = @"Write automatic UNIT-TESTS simply by highlighting your functionTest your ";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Manolov";
        public const string Tags = "";
    }
}
